name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build WAR
      run: mvn clean package

    - name: Check if WAR exists
      run: ls -lh target/*.war || echo "WAR not found!"

    - name: Deploy WAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "target/webapp-1.0-SNAPSHOT.war"
        target: "/home/ubuntu/tomcat/webapps/"
