name: Deploy WAR to EC2

on:
  push:
    branches:
      - main  # ya jis branch pe deploy karna hai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -f webapp/pom.xml

      - name: Verify WAR file
        run: ls -lh webapp/target/*.war || echo "WAR not found!"

      - name: Deploy WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2 IP ya hostname
          username: root                          # root user
          key: ${{ secrets.EC2_KEY }}             # private key in GitHub secrets
          port: 22
          source: "webapp/target/webapp.war"     # WAR file location
          target: "/root/tomcat/webapps/"         # EC2 target directory
