name: Build and Deploy WAR to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven
        run: mvn clean package

      - name: Check WAR file
        run: ls -lh webapp/target/*.war || echo "WAR not found!"

      - name: Deploy WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "webapp/target/webapp.war"
          target: "/root/tomcat/webapps/"

      - name: Restart Tomcat on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            #!/bin/bash
            echo "Stopping Tomcat..."
            # Find Tomcat java process and kill it
            pkill -f 'org.apache.catalina.startup.Bootstrap' || echo "Tomcat not running"
            sleep 5
            echo "Starting Tomcat..."
            /root/tomcat/bin/startup.sh
            echo "Tomcat restarted"
