name: Build and Deploy WAR to EC2

on:
  push:
    branches:
      - main   # apni branch yahan daal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn clean package

    - name: List WAR file
      run: ls -lh webapp/target/*.war || echo "WAR not found!"

    - name: Copy WAR to EC2 using SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: root                     # ROOT user yahan set kiya
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "webapp/target/webapp.war"
        target: "/root/tomcat/webapps/"    # Root ke tomcat webapps folder ka path

    - name: Restart Tomcat service on EC2 as root
      run: |
        ssh -i ${{ secrets.EC2_KEY }} -o StrictHostKeyChecking=no root@${{ secrets.EC2_HOST }} "sudo systemctl restart tomcat || /root/tomcat/bin/shutdown.sh && /root/tomcat/bin/startup.sh"
